controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: '/api'
    name_prefix: 'api_'
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
